id: b0297c109ca148799b771fd3c63a590b
initial_creation_type: ebook
created_at: 27/05/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmp1zi7ecpp.jpg
  credit: tmp5esobq82.jpg
